name: CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
          POSTGRES_DB: simple_bank
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version: "^1.21"
        id: go

      - name: Install golang-migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.16.2/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/bin/migrate
          which migrate

      - name: Run migrations
        run: make migrate_up

      - name: Test
        run: make test

  deploy:
    name: Build & deploy image
    runs-on: ubuntu-latest
    needs:
      - test
    env:
      NEW_VER: sha-$GITHUB_SHA
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          path: simple-bank

      - name: Checkout gitops repo
        uses: actions/checkout@v4
        with:
          path: gitops
          repository: firsttimeeagle-corp/gitops
          token: ${{ secrets.GH_ACTIONS_PAT }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/simple-bank
          tags: |
            type=sha,format=long

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./simple-bank
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Update doppler secrets
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_DEV_TOKEN }}
        run: doppler secrets set APP_VERSION="${{ env.NEW_VER }}"

      - name: Push new image version to gitops
        working-directory: ./gitops
        run: |
          sed -i -e "s/newTag:.*/newTag: ${{ env.NEW_VER }}/g" environments/dev/simple-bank/kustomization.yaml
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update simple-bank dev to ${{ env.NEW_VER }}"
          git push