name: Pre-release Workflow

on:
  workflow_dispatch:
  release:
    types:
      - "prereleased"

jobs:
  deploy:
    name: Deploy to staging
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Get latest SHA
        run: |
          echo "Latest commit SHA: $GITHUB_SHA"