name: Pre-release Workflow

on:
  workflow_dispatch:
  release:
    types:
      - "prereleased"

jobs:
  deploy:
    name: Deploy to staging
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: echo "Deployed to staging"