name: Pre-release

on:
  workflow_dispatch:
  release:
    types:
      - "prereleased"

jobs:
  deploy:
    name: Deploy to staging
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Promote new image tag
        env:
          OLD_IMAGE: brizaldi/simple-bank:sha-$GITHUB_SHA
          NEW_IMAGE: brizaldi/simple-bank:${{ github.event.release.tag_name }}
        run: |
          docker pull $OLD_IMAGE
          docker tag $OLD_IMAGE $NEW_IMAGE
          docker push $NEW_IMAGE