name: Pre-release

on:
  workflow_dispatch:
  release:
    types:
      - "prereleased"

jobs:
  deploy:
    name: Deploy to staging
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Promote image
        run: |
          ./upgrade-gitops-version.sh staging sha-$GITHUB_SHA ${{ github.event.release.tag_name }}