name: Pre-release

on:
  release:
    types:
      - "prereleased"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
          POSTGRES_DB: simple_bank
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version: "^1.21"
        id: go

      - name: Install golang-migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.16.2/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/bin/migrate
          which migrate

      - name: Run migrations
        run: make migrate_up

      - name: Test
        run: make test

  deploy:
    name: Build staging
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Checkout gitops repo
        uses: actions/checkout@v4
        with:
          repository: firsttimeeagle-corp/gitops
          token: ${{ secrets.GH_ACTIONS_PAT }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Promote new image tag
        env:
          OLD_IMAGE: brizaldi/simple-bank:sha-$GITHUB_SHA
          NEW_IMAGE: brizaldi/simple-bank:${{ github.event.release.tag_name }}-pre
        run: |
          docker pull ${{ env.OLD_IMAGE }}
          docker tag ${{ env.OLD_IMAGE }} ${{ env.NEW_IMAGE }}
          docker push ${{ env.NEW_IMAGE }}
      
      - name: Push new image version to gitops
        env:
          NEW_VER: ${{ github.event.release.tag_name }}-pre
        run: |
          sed -i -e "s/newTag:.*/newTag: ${{ env.NEW_VER }}/g" environments/staging/simple-bank/kustomization.yaml
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update simple-bank staging to ${{ env.NEW_VER }}"
          git push