name: Release

on:
  release:
    types:
      - "released"

jobs:
  deploy:
    name: Deploy to production
    runs-on: ubuntu-latest
    steps:
      - name: Check release type
        run: |
          echo ${{ github.event.release.type }}