name: Release

on:
  release:
    types:
      - "released"
      - "prereleased"

jobs:
  deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gitops repo
        uses: actions/checkout@v4
        with:
          repository: firsttimeeagle-corp/gitops
          token: ${{ secrets.GH_ACTIONS_PAT }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Promote new image tag
        env:
          OLD_IMAGE: brizaldi/simple-bank:sha-$GITHUB_SHA
          NEW_IMAGE: brizaldi/simple-bank:${{ github.event.release.tag_name }}
        run: |
          docker pull ${{ env.OLD_IMAGE }}
          docker tag ${{ env.OLD_IMAGE }} ${{ env.NEW_IMAGE }}
          docker push ${{ env.NEW_IMAGE }}
      
      - name: Push new image version to gitops
        env:
          NEW_VER: ${{ github.event.release.tag_name }}
        run: |
          [[ ${{ github.event.release.prerelease }} ]] && env="staging" || env="prod"
          sed -i -e "s/newTag:.*/newTag: ${{ env.NEW_VER }}/g" environments/$env/simple-bank/kustomization.yaml
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update simple-bank $env to ${{ env.NEW_VER }}"
          git push